HappyBrownies/TrabajoFinal/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabajoFinal.Controllers
{
    public class ProductosController : Controller
    {
        private Models.BDPastelEntities1 bd = new Models.BDPastelEntities1();
        // GET: Productos
        public ActionResult productos(string categor="")
        {
            var productos = bd.Producto.Take(20).ToList();
            ViewBag.listacategoria = bd.Categoria.ToList();
            ViewBag.categ = categor;
            return View(productos);
        }
    }
}

HappyBrownies/TrabajoFinal/Controllers/RealizarPagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabajoFinal.Controllers
{
    public class RealizarPagoController : Controller
    {
        private Models.BDPastelEntities1 bd = new Models.BDPastelEntities1();
        // GET: RealizarPago
        public ActionResult realizarpago()
        {
            var cliente = bd.Cliente.Find(Helper.SessionHelper.GetUser());
           
            return View(cliente);
        }
        [HttpPost]
        public JsonResult RealizarPedido(List<Pedido> p)
        {
            // guardar en base de datos
            var clienteid = Helper.SessionHelper.GetUser();
            var pcab = new Models.Pedido
            {
                ClienteId = clienteid,
                Estado = "P",
                Fecha = DateTime.Now
            };

            bd.Pedido.Add(pcab);
            bd.SaveChanges();


            foreach (var item in p)
            {
                var pdet = new Models.PedidoDetalle
                {
                    PedidoId = pcab.PedidoId,
                    Cantidad = item.Cantidad,
                    ProductoId = item.ProductoId
                };
                bd.PedidoDetalle.Add(pdet);
                bd.SaveChanges();
            }
          
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        public class Pedido
        {
            public int ProductoId { get; set; }
            public string Denominacion { get; set; }
            public int Cantidad { get; set; }
            public string Imagen { get; set; }
            public decimal Precio { get; set; }
        }

    }
}

HappyBrownies/TrabajoFinal/Controllers/VerCarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabajoFinal.Controllers
{
    public class VerCarritoController : Controller
    {
        // GET: VerCarrito
        public ActionResult vercarrito()
        {
            return View();
        }
    }
}

HappyBrownies/TrabajoFinal/Views/VerCarrito/pruebax.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>CamPastel</title>
    <meta charset="utf-8">
    <meta name="description" content="Plus E-Commerce Template">
    <meta name="author" content="Diamant Gjota" />
    <meta name="keywords" content="plus, html5, css3, template, ecommerce, e-commerce, bootstrap, responsive, creative" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!--Favicon-->
    <link rel="shortcut icon" href="~/img/logocabecera.png" type="image/x-icon">
    <link rel="icon" href="~/img/logocabecera.png" type="image/x-icon">

    <!-- css files -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/owl.carousel.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/owl.theme.default.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/animate.css" />
    <link rel="stylesheet" type="text/css" href="~/css/swiper.css" />

    <!-- this is default skin you can replace that with: dark.css, yellow.css, red.css ect -->
    <link id="pagestyle" rel="stylesheet" type="text/css" href="~/css/default.css" />


</head>
<body>

    <!-- Cabecera -->
    <div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Pages</a></li>
                        <li class="active">Carrito</li>
                    </ul><!-- end breadcrumb -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end breadcrumbs -->
    <!-- start section -->
    <section class="section white-backgorund">
        <div class="container">
            <div class="row">
                <!-- start sidebar -->
                <div class="col-sm-3">
                    <div class="widget">
                        <h6 class="subtitle">Mi Cuenta</h6>

                        <ul class="list list-unstyled">
                            <li>
                                <a href="my-account.html">Mi Cuenta</a>
                            </li>
                            <li class="active">
                                <a href="cart.html">Mi Carrito <span class="text-primary">(3)</span></a>
                            </li>
                            <li>
                                <a href="order-list.html">Mis Pedidos</a>
                            </li>
                            <li>
                                <a href="wishlist.html">Lista de Deseos <span class="text-primary">(5)</span></a>
                            </li>
                            <li>
                                <a href="user-information.html">Configuraciones</a>
                            </li>
                        </ul>
                    </div><!-- end widget -->



                    <div class="widget">
                        <h6 class="subtitle">Recientes</h6>

                        <ul class="items">
                            <li>
                                <a href="shop-single-product-v1.html" class="product-image">
                                    <img src="~/img/products/men_01.jpg" alt="Sample Product ">
                                </a>
                                <div class="product-details">
                                    <p class="product-name">
                                        <a href="shop-single-product-v1.html">Pastel de Naranja</a>
                                    </p>
                                    <span class="price text-primary">$19.99</span>
                                    <div class="rate text-warning">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                </div>
                            </li><!-- end item -->
                            <li>
                                <a href="shop-single-product-v1.html" class="product-image">
                                    <img src="~/img/products/women_02.jpg" alt="Sample Product ">
                                </a>
                                <div class="product-details">
                                    <p class="product-name">
                                        <a href="shop-single-product-v1.html">Product name</a>
                                    </p>
                                    <span class="price text-primary">$19.99</span>
                                    <div class="rate text-warning">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                </div>
                            </li><!-- end item -->
                        </ul>

                        <hr class="spacer-10 no-border">
                        <a href="shop-sidebar-left.html" class="btn btn-default btn-block semi-circle btn-md">Todos los Pasteles</a>
                    </div><!-- end widget -->
                </div><!-- end col -->
                <!-- end sidebar -->
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-12 text-left">
                            <h2 class="title">Mi Carrito</h2>
                        </div><!-- end col -->
                    </div><!-- end row -->

                    <hr class="spacer-5"><hr class="spacer-20 no-border">

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Producto</th>
                                            <th><div class="align-center">Cantidad</div></th>
                                            <th><div class="align-right">Precio</div></th>
                                        </tr>

                                    </thead>

                                    <tbody id="itemcarrito"></tbody>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td class="stronger">Total:</td>
                                        <td class="stronger"><div id="totalCompra" class="size-16 align-right">0.00</div></td>
                                    </tr>

                                </table><!-- end table -->
                            </div><!-- end table-responsive -->

                            <hr class="spacer-10 no-border">

                            <a href="@Url.Action("productos","Productos")" class="btn btn-light semi-circle btn-md pull-left">
                                <i class="fa fa-arrow-left mr-5"></i> Continua Comprando
                            </a>

                            <a href="@Url.Action("realizarpago","RealizarPago")" class="btn btn-default semi-circle btn-md pull-right">
                                Realizar Pago <i class="fa fa-arrow-right ml-5"></i>
                            </a>
                        </div><!-- end col -->
                    </div><!-- end row -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->

    </section>
    <!-- end section -->

    <!-- JavaScript Files -->
    <script type="text/javascript" src="~/js/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/js/jquery.downCount.js"></script>
    <script type="text/javascript" src="~/js/nouislider.min.js"></script>
    <script type="text/javascript" src="~/js/jquery.sticky.js"></script>
    <script type="text/javascript" src="~/js/pace.min.js"></script>
    <script type="text/javascript" src="~/js/star-rating.min.js"></script>
    <script type="text/javascript" src="~/js/wow.min.js"></script>
    @*<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>*@
    <script type="text/javascript" src="~/js/gmaps.js"></script>
    <script type="text/javascript" src="~/js/swiper.min.js"></script>
    <script type="text/javascript" src="~/js/main.js"></script>

    <script>
        $(function () {
            var carrito = localStorage.getItem("carrito");
            var productos = [];
            if (carrito != null) {
                productos = JSON.parse(carrito);
                CargarProductos(productos);
            }
        });
        function CargarProductos(productos) {
            var html = '';
            var total = 0;

            $.each(productos, function () {
                total += this.Precio * this.Cantidad
                html += '<tr>' +
                '            <td class="image"><img src="/ImgProductos/' + this.Imagen + '" alt="" width="124" height="124" /></td>' +
                '            <td class="desc">' + this.Denominacion + ' &nbsp; <a title="Remove Item" class="icon-remove-sign" href="#"></a></td>' +
                '            <td class="qty">' +
                '                <input type="text" class="tiny-size" value="' + this.Cantidad + '" />' +
                '           </td>' +
                '           <td class="price">S/. ' + this.Precio + '</td>' +
                '          </tr>'
            });
            $('#itemcarrito').html(html);

            $("#totalCompra").text('S/.' + total);
        }
    </script>


</body>

</html>