HappyBrownies/TrabajoFinal/Areas/loginadmin/Controllers/loginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabajoFinal.Areas.loginadmin.Controllers
{
    public class loginController : Controller
    {
        private Models.BDPastelEntities1 bd = new Models.BDPastelEntities1();
        // GET: loginadmin/login
        //public ActionResult login()
        //{
        //    return View();
        //}

        public ActionResult Login(string usuario, string clave)
        {
            ViewBag.nombre= bd.Usuario.FirstOrDefault(x => x.Nickname == usuario && x.Clave == clave);
            var u = bd.Usuario.FirstOrDefault(x => x.Nickname == usuario && x.Clave == clave);
            if (u != null)
            {
                Helper.SessionHelper.AddUserToSession(u.UsuarioId.ToString());
                return RedirectToAction("inicio", "pagina", new { Area = "Admin", ViewBag.nombre });
               
            }else {
                return RedirectToAction("cuentaadmin", "CuentaAdmin", new { Area = "loginadmin" });
            }
           
        }
        public ActionResult Logout()
        {
            Helper.SessionHelper.DestroyUserSession();
            return RedirectToAction("cuentaadmin", "CuentaAdmin", new { Area = "loginadmin" });
        }
        public static string ObtenerNombreUsuario()
        {
            using (var b = new Models.BDPastelEntities1())
            {
                return b.Usuario.Find(Helper.SessionHelper.GetUser()).Nickname;
            }
        }
    }
}

HappyBrownies/TrabajoFinal/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabajoFinal.Controllers
{
    public class CuentaController : Controller
    {
        private Models.BDPastelEntities1 bd = new Models.BDPastelEntities1();
        // GET: Cuenta
        public ActionResult login()
        {
            return View();
        }
        public ActionResult registrar()
        {
            return View();
        }
        public ActionResult vercuentacliente()
        {
            var cliente = bd.Cliente.Find(Helper.SessionHelper.GetUser());

           
            return View(cliente);
        }
    }
}

HappyBrownies/TrabajoFinal/Controllers/VerCarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabajoFinal.Controllers
{
    public class VerCarritoController : Controller
    {
        // GET: VerCarrito
        public ActionResult vercarrito()
        {
            return View();
        }
    }
}

HappyBrownies/TrabajoFinal/Views/Cuenta/login.cshtml
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Pages</a></li>
                    <li class="active">Login</li>
                </ul><!-- end breadcrumb -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end breadcrumbs -->
<!-- start section -->
<section class="section white-backgorund">
    <div class="container">
        <div class="row">
            <!-- start sidebar -->
            <div class="col-sm-3">
                
            </div><!-- end col -->
            <!-- end sidebar -->
            <div class="col-sm-9">
                <div class="row">
                    <div class="col-sm-12 text-left">
                        <h2 class="title">Ingrese con su Cuenta</h2>
                    </div><!-- end col -->
                </div><!-- end row -->

                <hr class="spacer-5"><hr class="spacer-20 no-border">

                <div class="modal-body">
                    <div class="col-sm-12 col-md-10 col-lg-8">
                        <form  method="post" action="@Url.Action("Login","Home")"  class="form-horizontal">
                            <div class="form-group">
                                <label for="email" class="col-sm-2 control-label">Usuario</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-md" name="usuario" placeholder="Usuario" />
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <label for="password" class="col-sm-2 control-label">Password</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control input-md" name="clave" placeholder="Password" />
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <div class="checkbox-input mb-10">
                                        <input id="remember" class="styled" type="checkbox">
                                        <label for="remember">
                                            Recuerdeme
                                        </label>
                                    </div><!-- end checkbox-input -->
                                </div><!-- end col -->
                                <div class="col-sm-offset-2 col-sm-10">
                                    <label><a href="@Url.Action("registrar","Cuenta")">Registrese</a></label>
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-default round btn-md"><i class="fa fa-lock mr-5"></i> Iniciar Sesion</button>
                                </div>
                            </div><!-- end form-group -->
                        </form>
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<!-- end section -->

HappyBrownies/TrabajoFinal/Views/Cuenta/registrar.cshtml
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Pages</a></li>
                    <li class="active">Registrar</li>
                </ul><!-- end breadcrumb -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end breadcrumbs -->
<!-- start section -->
<section class="section white-backgorund">
    <div class="container">
        <div class="row">
            <!-- start sidebar -->
            <div class="col-sm-3">
               
            </div><!-- end col -->
            <!-- end sidebar -->
            <div class="col-sm-9">
                <div class="row">
                    <div class="col-sm-12 text-left">
                        <h2 class="title">Crear una Cuenta</h2>
                    </div><!-- end col -->
                </div><!-- end row -->

                <hr class="spacer-5"><hr class="spacer-20 no-border">

                <div class="row">
                    <div class="col-sm-12 col-md-10 col-lg-12">
                        <form method="post" action="@Url.Action("RegistrarCliente","Home")" class="form-horizontal">
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Nombre</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-md" name="Nombres" placeholder="Nombre">
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Apellidos</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-md" name="Apellidos" placeholder="Apellidos" />
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Usuario</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-md" name="Usuario" placeholder="Usuario" />
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Password</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control input-md" name="Clave" placeholder="Password" />
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control input-md" name="Correo" placeholder="Email" />
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Celular</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-md" name="Celular" placeholder="celular" />
                                </div>
                            </div><!-- end form-group -->
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Direccion</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-md" name="Direccion" placeholder="Direccion" />
                                </div>
                            </div><!-- end form-group -->


                      
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-default round btn-md"><i class="fa fa-user mr-5"></i> Crear Cuenta</button>
                                </div>
                            </div><!-- end form-group -->
                        </form>
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>
<!-- end section -->

HappyBrownies/TrabajoFinal/Views/Cuenta/vercuentacliente.cshtml
@model  TrabajoFinal.Models.Cliente
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Pages</a></li>
                    <li class="active">User Information</li>
                </ul><!-- end breadcrumb -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end breadcrumbs -->
<!-- start section -->
<section class="section white-backgorund">
    <div class="container">
        <div class="row">
            <!-- start sidebar -->
            <div class="col-sm-3">
                <div class="widget">
                    <h6 class="subtitle">Account Navigation</h6>

                    <ul class="list list-unstyled">
                        <li>
                            <a href="@Url.Action("vercuentacliente", "Cuenta")">Mi Cuenta</a>
                        </li>
                        <li class="active">
                            <a href="@Url.Action("vercarrito", "VerCarrito")">Mi Carrito <span  class="text-primary"></span></a>
                        </li>
                        <li>
                            <a href="order-list.html">Mis Pedidos</a>
                        </li>
                      
                       
                    </ul>
                </div><!-- end widget -->

           
            </div><!-- end col -->
            <!-- end sidebar -->
            <div class="col-sm-9">
                <div class="row">
                    <div class="col-sm-12 text-left">
                        <h2 class="title">Mi Informacion Personal</h2>
                    </div><!-- end col -->
                </div><!-- end row -->

                <hr class="spacer-5"><hr class="spacer-20 no-border">

                <div class="row">
                    <div class="col-md-8">

                            <div class="form-group">
                                <label for="email" class="col-sm-2 control-label">Nombre</label>
                                <div class="col-sm-10">
                                    <input type="text" id="firstName" placeholder="Nombre" class="form-control input-md required" required="" value='@Model.Nombres  @Model.Apellidos' />
                                </div>
                            </div><!-- end form-group -->
                        <hr class="spacer-5"><hr class="spacer-20 no-border">

                            <div class="form-group">
                                <label for="email" class="col-sm-2 control-label">Telefono</label>
                                <div class="col-sm-10">
                                    <input type="tel" id="telephone" placeholder="Telefono" class="form-control input-md required" required="" value="@Model.Celular" />
                                </div><!-- end form-group -->
                            </div>
                        <hr class="spacer-5"><hr class="spacer-20 no-border">

                            <div class="form-group">
                                <label for="email" class="col-sm-2 control-label">Correo</label>
                                <div class="col-sm-10">

                                    <input type="email" id="email" placeholder="Email" class="form-control input-md required" required="" value="@Model.Correo" />
                                </div><!-- end form-group -->
                            </div>
                        <hr class="spacer-5"><hr class="spacer-20 no-border">

                            <div class="form-group">
                                <label for="email" class="col-sm-2 control-label">Direccion</label>
                                <div class="col-sm-10">
                                    <input type="text" id="addr1" placeholder="Direccion 1" class="form-control input-md required" required="" value="@Model.Direccion" />
                                </div>
                            </div>
                        <hr class="spacer-5"><hr class="spacer-20 no-border">
                    </div>

             
                </div><!-- end row -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>